In [ ]:
# data 2019-2023
import pandas as pd


path1 = "/Users/crystalguo/Downloads/archive (1)/flights_sample_3m.csv"
df1 = pd.read_csv(path1)

path2 = "/Users/crystalguo/Downloads/archive (1)/flight_data_2024.csv"
df2 = pd.read_csv(path2)

/var/folders/q4/t7g5qths559gsjx7h006w5w40000gn/T/ipykernel_64348/1532923608.py:12: DtypeWarning: Columns (0: cancellation_code) have mixed types. Specify dtype option on import or set low_memory=False.
  df2 = pd.read_csv(path2)

In [13]:

pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

print("Columns:")
print(df1.columns.tolist())

print("\nFirst 10 rows:")
print(df1.head(10))

print(df1.head(10).T)

Columns:
['FL_DATE', 'AIRLINE', 'AIRLINE_DOT', 'AIRLINE_CODE', 'DOT_CODE', 'FL_NUMBER', 'ORIGIN', 'ORIGIN_CITY', 'DEST', 'DEST_CITY', 'CRS_DEP_TIME', 'DEP_TIME', 'DEP_DELAY', 'TAXI_OUT', 'WHEELS_OFF', 'WHEELS_ON', 'TAXI_IN', 'CRS_ARR_TIME', 'ARR_TIME', 'ARR_DELAY', 'CANCELLED', 'CANCELLATION_CODE', 'DIVERTED', 'CRS_ELAPSED_TIME', 'ELAPSED_TIME', 'AIR_TIME', 'DISTANCE', 'DELAY_DUE_CARRIER', 'DELAY_DUE_WEATHER', 'DELAY_DUE_NAS', 'DELAY_DUE_SECURITY', 'DELAY_DUE_LATE_AIRCRAFT']

First 10 rows:
      FL_DATE                 AIRLINE                 AIRLINE_DOT  \
0  2019-01-09   United Air Lines Inc.   United Air Lines Inc.: UA
1  2022-11-19    Delta Air Lines Inc.    Delta Air Lines Inc.: DL
2  2022-07-22   United Air Lines Inc.   United Air Lines Inc.: UA
3  2023-03-06    Delta Air Lines Inc.    Delta Air Lines Inc.: DL
4  2020-02-23        Spirit Air Lines        Spirit Air Lines: NK
5  2019-07-31  Southwest Airlines Co.  Southwest Airlines Co.: WN
6  2023-06-11  American Airlines Inc.  American Airlines Inc.: AA
7  2019-07-08        Republic Airline        Republic Airline: YX
8  2023-02-12        Spirit Air Lines        Spirit Air Lines: NK
9  2020-08-22    Alaska Airlines Inc.    Alaska Airlines Inc.: AS

  AIRLINE_CODE  DOT_CODE  FL_NUMBER ORIGIN          ORIGIN_CITY DEST  \
0           UA     19977       1562    FLL  Fort Lauderdale, FL  EWR
1           DL     19790       1149    MSP      Minneapolis, MN  SEA
2           UA     19977        459    DEN           Denver, CO  MSP
3           DL     19790       2295    MSP      Minneapolis, MN  SFO
4           NK     20416        407    MCO          Orlando, FL  DFW
5           WN     19393        665    DAL           Dallas, TX  OKC
6           AA     19805       2134    DCA       Washington, DC  BOS
7           YX     20452       4464    HSV       Huntsville, AL  DCA
8           NK     20416        590    IAH          Houston, TX  LAX
9           AS     19930        223    SEA          Seattle, WA  FAI

               DEST_CITY  CRS_DEP_TIME  DEP_TIME  DEP_DELAY  TAXI_OUT  \
0             Newark, NJ          1155    1151.0       -4.0      19.0
1            Seattle, WA          2120    2114.0       -6.0       9.0
2        Minneapolis, MN           954    1000.0        6.0      20.0
3      San Francisco, CA          1609    1608.0       -1.0      27.0
4  Dallas/Fort Worth, TX          1840    1838.0       -2.0      15.0
5      Oklahoma City, OK          1010    1237.0      147.0      15.0
6             Boston, MA          1010    1001.0       -9.0      23.0
7         Washington, DC          1643    1637.0       -6.0      22.0
8        Los Angeles, CA           530     527.0       -3.0      11.0
9          Fairbanks, AK          2125    2116.0       -9.0      19.0

   WHEELS_OFF  WHEELS_ON  TAXI_IN  CRS_ARR_TIME  ARR_TIME  ARR_DELAY  \
0      1210.0     1443.0      4.0          1501    1447.0      -14.0
1      2123.0     2232.0     38.0          2315    2310.0       -5.0
2      1020.0     1247.0      5.0          1252    1252.0        0.0
3      1635.0     1844.0      9.0          1829    1853.0       24.0
4      1853.0     2026.0     14.0          2041    2040.0       -1.0
5      1252.0     1328.0      3.0          1110    1331.0      141.0
6      1024.0     1122.0      8.0          1159    1130.0      -29.0
7      1659.0     1927.0     41.0          1945    2008.0       23.0
8       538.0      658.0      8.0           717     706.0      -11.0
9      2135.0     2353.0      3.0          2355    2356.0        1.0

   CANCELLED CANCELLATION_CODE  DIVERTED  CRS_ELAPSED_TIME  ELAPSED_TIME  \
0        0.0               NaN       0.0             186.0         176.0
1        0.0               NaN       0.0             235.0         236.0
2        0.0               NaN       0.0             118.0         112.0
3        0.0               NaN       0.0             260.0         285.0
4        0.0               NaN       0.0             181.0         182.0
5        0.0               NaN       0.0              60.0          54.0
6        0.0               NaN       0.0             109.0          89.0
7        0.0               NaN       0.0             122.0         151.0
8        0.0               NaN       0.0             227.0         219.0
9        0.0               NaN       0.0             210.0         220.0

   AIR_TIME  DISTANCE  DELAY_DUE_CARRIER  DELAY_DUE_WEATHER  DELAY_DUE_NAS  \
0     153.0    1065.0                NaN                NaN            NaN
1     189.0    1399.0                NaN                NaN            NaN
2      87.0     680.0                NaN                NaN            NaN
3     249.0    1589.0                0.0                0.0           24.0
4     153.0     985.0                NaN                NaN            NaN
5      36.0     181.0              141.0                0.0            0.0
6      58.0     399.0                NaN                NaN            NaN
7      88.0     613.0                0.0                0.0           23.0
8     200.0    1379.0                NaN                NaN            NaN
9     198.0    1533.0                NaN                NaN            NaN

   DELAY_DUE_SECURITY  DELAY_DUE_LATE_AIRCRAFT
0                 NaN                      NaN
1                 NaN                      NaN
2                 NaN                      NaN
3                 0.0                      0.0
4                 NaN                      NaN
5                 0.0                      0.0
6                 NaN                      NaN
7                 0.0                      0.0
8                 NaN                      NaN
9                 NaN                      NaN
                                                 0                         1  \
FL_DATE                                 2019-01-09                2022-11-19
AIRLINE                      United Air Lines Inc.      Delta Air Lines Inc.
AIRLINE_DOT              United Air Lines Inc.: UA  Delta Air Lines Inc.: DL
AIRLINE_CODE                                    UA                        DL
DOT_CODE                                     19977                     19790
FL_NUMBER                                     1562                      1149
ORIGIN                                         FLL                       MSP
ORIGIN_CITY                    Fort Lauderdale, FL           Minneapolis, MN
DEST                                           EWR                       SEA
DEST_CITY                               Newark, NJ               Seattle, WA
CRS_DEP_TIME                                  1155                      2120
DEP_TIME                                    1151.0                    2114.0
DEP_DELAY                                     -4.0                      -6.0
TAXI_OUT                                      19.0                       9.0
WHEELS_OFF                                  1210.0                    2123.0
WHEELS_ON                                   1443.0                    2232.0
TAXI_IN                                        4.0                      38.0
CRS_ARR_TIME                                  1501                      2315
ARR_TIME                                    1447.0                    2310.0
ARR_DELAY                                    -14.0                      -5.0
CANCELLED                                      0.0                       0.0
CANCELLATION_CODE                              NaN                       NaN
DIVERTED                                       0.0                       0.0
CRS_ELAPSED_TIME                             186.0                     235.0
ELAPSED_TIME                                 176.0                     236.0
AIR_TIME                                     153.0                     189.0
DISTANCE                                    1065.0                    1399.0
DELAY_DUE_CARRIER                              NaN                       NaN
DELAY_DUE_WEATHER                              NaN                       NaN
DELAY_DUE_NAS                                  NaN                       NaN
DELAY_DUE_SECURITY                             NaN                       NaN
DELAY_DUE_LATE_AIRCRAFT                        NaN                       NaN

                                                 2                         3  \
FL_DATE                                 2022-07-22                2023-03-06
AIRLINE                      United Air Lines Inc.      Delta Air Lines Inc.
AIRLINE_DOT              United Air Lines Inc.: UA  Delta Air Lines Inc.: DL
AIRLINE_CODE                                    UA                        DL
DOT_CODE                                     19977                     19790
FL_NUMBER                                      459                      2295
ORIGIN                                         DEN                       MSP
ORIGIN_CITY                             Denver, CO           Minneapolis, MN
DEST                                           MSP                       SFO
DEST_CITY                          Minneapolis, MN         San Francisco, CA
CRS_DEP_TIME                                   954                      1609
DEP_TIME                                    1000.0                    1608.0
DEP_DELAY                                      6.0                      -1.0
TAXI_OUT                                      20.0                      27.0
WHEELS_OFF                                  1020.0                    1635.0
WHEELS_ON                                   1247.0                    1844.0
TAXI_IN                                        5.0                       9.0
CRS_ARR_TIME                                  1252                      1829
ARR_TIME                                    1252.0                    1853.0
ARR_DELAY                                      0.0                      24.0
CANCELLED                                      0.0                       0.0
CANCELLATION_CODE                              NaN                       NaN
DIVERTED                                       0.0                       0.0
CRS_ELAPSED_TIME                             118.0                     260.0
ELAPSED_TIME                                 112.0                     285.0
AIR_TIME                                      87.0                     249.0
DISTANCE                                     680.0                    1589.0
DELAY_DUE_CARRIER                              NaN                       0.0
DELAY_DUE_WEATHER                              NaN                       0.0
DELAY_DUE_NAS                                  NaN                      24.0
DELAY_DUE_SECURITY                             NaN                       0.0
DELAY_DUE_LATE_AIRCRAFT                        NaN                       0.0

                                             4                           5  \
FL_DATE                             2020-02-23                  2019-07-31
AIRLINE                       Spirit Air Lines      Southwest Airlines Co.
AIRLINE_DOT               Spirit Air Lines: NK  Southwest Airlines Co.: WN
AIRLINE_CODE                                NK                          WN
DOT_CODE                                 20416                       19393
FL_NUMBER                                  407                         665
ORIGIN                                     MCO                         DAL
ORIGIN_CITY                        Orlando, FL                  Dallas, TX
DEST                                       DFW                         OKC
DEST_CITY                Dallas/Fort Worth, TX           Oklahoma City, OK
CRS_DEP_TIME                              1840                        1010
DEP_TIME                                1838.0                      1237.0
DEP_DELAY                                 -2.0                       147.0
TAXI_OUT                                  15.0                        15.0
WHEELS_OFF                              1853.0                      1252.0
WHEELS_ON                               2026.0                      1328.0
TAXI_IN                                   14.0                         3.0
CRS_ARR_TIME                              2041                        1110
ARR_TIME                                2040.0                      1331.0
ARR_DELAY                                 -1.0                       141.0
CANCELLED                                  0.0                         0.0
CANCELLATION_CODE                          NaN                         NaN
DIVERTED                                   0.0                         0.0
CRS_ELAPSED_TIME                         181.0                        60.0
ELAPSED_TIME                             182.0                        54.0
AIR_TIME                                 153.0                        36.0
DISTANCE                                 985.0                       181.0
DELAY_DUE_CARRIER                          NaN                       141.0
DELAY_DUE_WEATHER                          NaN                         0.0
DELAY_DUE_NAS                              NaN                         0.0
DELAY_DUE_SECURITY                         NaN                         0.0
DELAY_DUE_LATE_AIRCRAFT                    NaN                         0.0

                                                  6                     7  \
FL_DATE                                  2023-06-11            2019-07-08
AIRLINE                      American Airlines Inc.      Republic Airline
AIRLINE_DOT              American Airlines Inc.: AA  Republic Airline: YX
AIRLINE_CODE                                     AA                    YX
DOT_CODE                                      19805                 20452
FL_NUMBER                                      2134                  4464
ORIGIN                                          DCA                   HSV
ORIGIN_CITY                          Washington, DC        Huntsville, AL
DEST                                            BOS                   DCA
DEST_CITY                                Boston, MA        Washington, DC
CRS_DEP_TIME                                   1010                  1643
DEP_TIME                                     1001.0                1637.0
DEP_DELAY                                      -9.0                  -6.0
TAXI_OUT                                       23.0                  22.0
WHEELS_OFF                                   1024.0                1659.0
WHEELS_ON                                    1122.0                1927.0
TAXI_IN                                         8.0                  41.0
CRS_ARR_TIME                                   1159                  1945
ARR_TIME                                     1130.0                2008.0
ARR_DELAY                                     -29.0                  23.0
CANCELLED                                       0.0                   0.0
CANCELLATION_CODE                               NaN                   NaN
DIVERTED                                        0.0                   0.0
CRS_ELAPSED_TIME                              109.0                 122.0
ELAPSED_TIME                                   89.0                 151.0
AIR_TIME                                       58.0                  88.0
DISTANCE                                      399.0                 613.0
DELAY_DUE_CARRIER                               NaN                   0.0
DELAY_DUE_WEATHER                               NaN                   0.0
DELAY_DUE_NAS                                   NaN                  23.0
DELAY_DUE_SECURITY                              NaN                   0.0
DELAY_DUE_LATE_AIRCRAFT                         NaN                   0.0

                                            8                         9
FL_DATE                            2023-02-12                2020-08-22
AIRLINE                      Spirit Air Lines      Alaska Airlines Inc.
AIRLINE_DOT              Spirit Air Lines: NK  Alaska Airlines Inc.: AS
AIRLINE_CODE                               NK                        AS
DOT_CODE                                20416                     19930
FL_NUMBER                                 590                       223
ORIGIN                                    IAH                       SEA
ORIGIN_CITY                       Houston, TX               Seattle, WA
DEST                                      LAX                       FAI
DEST_CITY                     Los Angeles, CA             Fairbanks, AK
CRS_DEP_TIME                              530                      2125
DEP_TIME                                527.0                    2116.0
DEP_DELAY                                -3.0                      -9.0
TAXI_OUT                                 11.0                      19.0
WHEELS_OFF                              538.0                    2135.0
WHEELS_ON                               658.0                    2353.0
TAXI_IN                                   8.0                       3.0
CRS_ARR_TIME                              717                      2355
ARR_TIME                                706.0                    2356.0
ARR_DELAY                               -11.0                       1.0
CANCELLED                                 0.0                       0.0
CANCELLATION_CODE                         NaN                       NaN
DIVERTED                                  0.0                       0.0
CRS_ELAPSED_TIME                        227.0                     210.0
ELAPSED_TIME                            219.0                     220.0
AIR_TIME                                200.0                     198.0
DISTANCE                               1379.0                    1533.0
DELAY_DUE_CARRIER                         NaN                       NaN
DELAY_DUE_WEATHER                         NaN                       NaN
DELAY_DUE_NAS                             NaN                       NaN
DELAY_DUE_SECURITY                        NaN                       NaN
DELAY_DUE_LATE_AIRCRAFT                   NaN                       NaN

In [10]:
print(df1.head(10))

      FL_DATE                 AIRLINE                 AIRLINE_DOT  \
0  2019-01-09   United Air Lines Inc.   United Air Lines Inc.: UA
1  2022-11-19    Delta Air Lines Inc.    Delta Air Lines Inc.: DL
2  2022-07-22   United Air Lines Inc.   United Air Lines Inc.: UA
3  2023-03-06    Delta Air Lines Inc.    Delta Air Lines Inc.: DL
4  2020-02-23        Spirit Air Lines        Spirit Air Lines: NK
5  2019-07-31  Southwest Airlines Co.  Southwest Airlines Co.: WN
6  2023-06-11  American Airlines Inc.  American Airlines Inc.: AA
7  2019-07-08        Republic Airline        Republic Airline: YX
8  2023-02-12        Spirit Air Lines        Spirit Air Lines: NK
9  2020-08-22    Alaska Airlines Inc.    Alaska Airlines Inc.: AS

  AIRLINE_CODE  DOT_CODE  FL_NUMBER ORIGIN          ORIGIN_CITY DEST  \
0           UA     19977       1562    FLL  Fort Lauderdale, FL  EWR
1           DL     19790       1149    MSP      Minneapolis, MN  SEA
2           UA     19977        459    DEN           Denver, CO  MSP
3           DL     19790       2295    MSP      Minneapolis, MN  SFO
4           NK     20416        407    MCO          Orlando, FL  DFW
5           WN     19393        665    DAL           Dallas, TX  OKC
6           AA     19805       2134    DCA       Washington, DC  BOS
7           YX     20452       4464    HSV       Huntsville, AL  DCA
8           NK     20416        590    IAH          Houston, TX  LAX
9           AS     19930        223    SEA          Seattle, WA  FAI

               DEST_CITY  ...  DIVERTED  CRS_ELAPSED_TIME  ELAPSED_TIME  \
0             Newark, NJ  ...       0.0             186.0         176.0
1            Seattle, WA  ...       0.0             235.0         236.0
2        Minneapolis, MN  ...       0.0             118.0         112.0
3      San Francisco, CA  ...       0.0             260.0         285.0
4  Dallas/Fort Worth, TX  ...       0.0             181.0         182.0
5      Oklahoma City, OK  ...       0.0              60.0          54.0
6             Boston, MA  ...       0.0             109.0          89.0
7         Washington, DC  ...       0.0             122.0         151.0
8        Los Angeles, CA  ...       0.0             227.0         219.0
9          Fairbanks, AK  ...       0.0             210.0         220.0

   AIR_TIME  DISTANCE  DELAY_DUE_CARRIER  DELAY_DUE_WEATHER  DELAY_DUE_NAS  \
0     153.0    1065.0                NaN                NaN            NaN
1     189.0    1399.0                NaN                NaN            NaN
2      87.0     680.0                NaN                NaN            NaN
3     249.0    1589.0                0.0                0.0           24.0
4     153.0     985.0                NaN                NaN            NaN
5      36.0     181.0              141.0                0.0            0.0
6      58.0     399.0                NaN                NaN            NaN
7      88.0     613.0                0.0                0.0           23.0
8     200.0    1379.0                NaN                NaN            NaN
9     198.0    1533.0                NaN                NaN            NaN

   DELAY_DUE_SECURITY  DELAY_DUE_LATE_AIRCRAFT
0                 NaN                      NaN
1                 NaN                      NaN
2                 NaN                      NaN
3                 0.0                      0.0
4                 NaN                      NaN
5                 0.0                      0.0
6                 NaN                      NaN
7                 0.0                      0.0
8                 NaN                      NaN
9                 NaN                      NaN

[10 rows x 32 columns]

In [15]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", None)
pd.set_option("display.max_colwidth", None)

print("Columns:")
print(df2.columns.tolist())

print("\nFirst 10 rows:")
print(df2.head(10))

print(df2.head(10).T)

Columns:
['year', 'month', 'day_of_month', 'day_of_week', 'fl_date', 'op_unique_carrier', 'op_carrier_fl_num', 'origin', 'origin_city_name', 'origin_state_nm', 'dest', 'dest_city_name', 'dest_state_nm', 'crs_dep_time', 'dep_time', 'dep_delay', 'taxi_out', 'wheels_off', 'wheels_on', 'taxi_in', 'crs_arr_time', 'arr_time', 'arr_delay', 'cancelled', 'cancellation_code', 'diverted', 'crs_elapsed_time', 'actual_elapsed_time', 'air_time', 'distance', 'carrier_delay', 'weather_delay', 'nas_delay', 'security_delay', 'late_aircraft_delay']

First 10 rows:
   year  month  day_of_month  day_of_week     fl_date op_unique_carrier  \
0  2024      1             1            1  2024-01-01                9E
1  2024      1             1            1  2024-01-01                9E
2  2024      1             1            1  2024-01-01                9E
3  2024      1             1            1  2024-01-01                9E
4  2024      1             1            1  2024-01-01                9E
5  2024      1             1            1  2024-01-01                9E
6  2024      1             1            1  2024-01-01                9E
7  2024      1             1            1  2024-01-01                9E
8  2024      1             1            1  2024-01-01                9E
9  2024      1             1            1  2024-01-01                9E

   op_carrier_fl_num origin     origin_city_name origin_state_nm dest  \
0             4814.0    JFK         New York, NY        New York  DTW
1             4815.0    MSP      Minneapolis, MN       Minnesota  CLE
2             4817.0    JFK         New York, NY        New York  RIC
3             4817.0    RIC         Richmond, VA        Virginia  JFK
4             4818.0    DTW          Detroit, MI        Michigan  MKE
5             4822.0    JAX     Jacksonville, FL         Florida  LGA
6             4822.0    LGA         New York, NY        New York  JAX
7             4823.0    CHS       Charleston, SC  South Carolina  LGA
8             4823.0    LGA         New York, NY        New York  CHS
9             4828.0    ITH  Ithaca/Cortland, NY        New York  JFK

     dest_city_name   dest_state_nm  crs_dep_time  dep_time  dep_delay  \
0       Detroit, MI        Michigan          1252    1247.0       -5.0
1     Cleveland, OH            Ohio          1015    1001.0      -14.0
2      Richmond, VA        Virginia          1415    1411.0       -4.0
3      New York, NY        New York          1650    1643.0       -7.0
4     Milwaukee, WI       Wisconsin          1015    1010.0       -5.0
5      New York, NY        New York          1410    1403.0       -7.0
6  Jacksonville, FL         Florida           955     947.0       -8.0
7      New York, NY        New York          1140    1135.0       -5.0
8    Charleston, SC  South Carolina           815     810.0       -5.0
9      New York, NY        New York          1300    1248.0      -12.0

   taxi_out  wheels_off  wheels_on  taxi_in  crs_arr_time  arr_time  \
0      31.0      1318.0     1442.0      7.0          1508    1449.0
1      20.0      1021.0     1249.0      6.0          1325    1255.0
2      21.0      1432.0     1533.0      8.0          1601    1541.0
3      13.0      1656.0     1747.0     12.0          1841    1759.0
4      21.0      1031.0     1016.0      4.0          1034    1020.0
5      14.0      1417.0     1559.0      4.0          1627    1603.0
6      26.0      1013.0     1218.0     13.0          1244    1231.0
7       8.0      1143.0     1309.0      5.0          1338    1314.0
8      14.0       824.0     1005.0      8.0          1044    1013.0
9      12.0      1300.0     1343.0     12.0          1419    1355.0

   arr_delay  cancelled cancellation_code  diverted  crs_elapsed_time  \
0      -19.0          0               NaN         0             136.0
1      -30.0          0               NaN         0             130.0
2      -20.0          0               NaN         0             106.0
3      -42.0          0               NaN         0             111.0
4      -14.0          0               NaN         0              79.0
5      -24.0          0               NaN         0             137.0
6      -13.0          0               NaN         0             169.0
7      -24.0          0               NaN         0             118.0
8      -31.0          0               NaN         0             149.0
9      -24.0          0               NaN         0              79.0

   actual_elapsed_time  air_time  distance  carrier_delay  weather_delay  \
0                122.0      84.0     509.0              0              0
1                114.0      88.0     622.0              0              0
2                 90.0      61.0     288.0              0              0
3                 76.0      51.0     288.0              0              0
4                 70.0      45.0     237.0              0              0
5                120.0     102.0     833.0              0              0
6                164.0     125.0     833.0              0              0
7                 99.0      86.0     641.0              0              0
8                123.0     101.0     641.0              0              0
9                 67.0      43.0     189.0              0              0

   nas_delay  security_delay  late_aircraft_delay
0          0               0                    0
1          0               0                    0
2          0               0                    0
3          0               0                    0
4          0               0                    0
5          0               0                    0
6          0               0                    0
7          0               0                    0
8          0               0                    0
9          0               0                    0
                                0                1             2  \
year                         2024             2024          2024
month                           1                1             1
day_of_month                    1                1             1
day_of_week                     1                1             1
fl_date                2024-01-01       2024-01-01    2024-01-01
op_unique_carrier              9E               9E            9E
op_carrier_fl_num          4814.0           4815.0        4817.0
origin                        JFK              MSP           JFK
origin_city_name     New York, NY  Minneapolis, MN  New York, NY
origin_state_nm          New York        Minnesota      New York
dest                          DTW              CLE           RIC
dest_city_name        Detroit, MI    Cleveland, OH  Richmond, VA
dest_state_nm            Michigan             Ohio      Virginia
crs_dep_time                 1252             1015          1415
dep_time                   1247.0           1001.0        1411.0
dep_delay                    -5.0            -14.0          -4.0
taxi_out                     31.0             20.0          21.0
wheels_off                 1318.0           1021.0        1432.0
wheels_on                  1442.0           1249.0        1533.0
taxi_in                       7.0              6.0           8.0
crs_arr_time                 1508             1325          1601
arr_time                   1449.0           1255.0        1541.0
arr_delay                   -19.0            -30.0         -20.0
cancelled                       0                0             0
cancellation_code             NaN              NaN           NaN
diverted                        0                0             0
crs_elapsed_time            136.0            130.0         106.0
actual_elapsed_time         122.0            114.0          90.0
air_time                     84.0             88.0          61.0
distance                    509.0            622.0         288.0
carrier_delay                   0                0             0
weather_delay                   0                0             0
nas_delay                       0                0             0
security_delay                  0                0             0
late_aircraft_delay             0                0             0

                                3              4                 5  \
year                         2024           2024              2024
month                           1              1                 1
day_of_month                    1              1                 1
day_of_week                     1              1                 1
fl_date                2024-01-01     2024-01-01        2024-01-01
op_unique_carrier              9E             9E                9E
op_carrier_fl_num          4817.0         4818.0            4822.0
origin                        RIC            DTW               JAX
origin_city_name     Richmond, VA    Detroit, MI  Jacksonville, FL
origin_state_nm          Virginia       Michigan           Florida
dest                          JFK            MKE               LGA
dest_city_name       New York, NY  Milwaukee, WI      New York, NY
dest_state_nm            New York      Wisconsin          New York
crs_dep_time                 1650           1015              1410
dep_time                   1643.0         1010.0            1403.0
dep_delay                    -7.0           -5.0              -7.0
taxi_out                     13.0           21.0              14.0
wheels_off                 1656.0         1031.0            1417.0
wheels_on                  1747.0         1016.0            1559.0
taxi_in                      12.0            4.0               4.0
crs_arr_time                 1841           1034              1627
arr_time                   1759.0         1020.0            1603.0
arr_delay                   -42.0          -14.0             -24.0
cancelled                       0              0                 0
cancellation_code             NaN            NaN               NaN
diverted                        0              0                 0
crs_elapsed_time            111.0           79.0             137.0
actual_elapsed_time          76.0           70.0             120.0
air_time                     51.0           45.0             102.0
distance                    288.0          237.0             833.0
carrier_delay                   0              0                 0
weather_delay                   0              0                 0
nas_delay                       0              0                 0
security_delay                  0              0                 0
late_aircraft_delay             0              0                 0

                                    6               7               8  \
year                             2024            2024            2024
month                               1               1               1
day_of_month                        1               1               1
day_of_week                         1               1               1
fl_date                    2024-01-01      2024-01-01      2024-01-01
op_unique_carrier                  9E              9E              9E
op_carrier_fl_num              4822.0          4823.0          4823.0
origin                            LGA             CHS             LGA
origin_city_name         New York, NY  Charleston, SC    New York, NY
origin_state_nm              New York  South Carolina        New York
dest                              JAX             LGA             CHS
dest_city_name       Jacksonville, FL    New York, NY  Charleston, SC
dest_state_nm                 Florida        New York  South Carolina
crs_dep_time                      955            1140             815
dep_time                        947.0          1135.0           810.0
dep_delay                        -8.0            -5.0            -5.0
taxi_out                         26.0             8.0            14.0
wheels_off                     1013.0          1143.0           824.0
wheels_on                      1218.0          1309.0          1005.0
taxi_in                          13.0             5.0             8.0
crs_arr_time                     1244            1338            1044
arr_time                       1231.0          1314.0          1013.0
arr_delay                       -13.0           -24.0           -31.0
cancelled                           0               0               0
cancellation_code                 NaN             NaN             NaN
diverted                            0               0               0
crs_elapsed_time                169.0           118.0           149.0
actual_elapsed_time             164.0            99.0           123.0
air_time                        125.0            86.0           101.0
distance                        833.0           641.0           641.0
carrier_delay                       0               0               0
weather_delay                       0               0               0
nas_delay                           0               0               0
security_delay                      0               0               0
late_aircraft_delay                 0               0               0

                                       9
year                                2024
month                                  1
day_of_month                           1
day_of_week                            1
fl_date                       2024-01-01
op_unique_carrier                     9E
op_carrier_fl_num                 4828.0
origin                               ITH
origin_city_name     Ithaca/Cortland, NY
origin_state_nm                 New York
dest                                 JFK
dest_city_name              New York, NY
dest_state_nm                   New York
crs_dep_time                        1300
dep_time                          1248.0
dep_delay                          -12.0
taxi_out                            12.0
wheels_off                        1300.0
wheels_on                         1343.0
taxi_in                             12.0
crs_arr_time                        1419
arr_time                          1355.0
arr_delay                          -24.0
cancelled                              0
cancellation_code                    NaN
diverted                               0
crs_elapsed_time                    79.0
actual_elapsed_time                 67.0
air_time                            43.0
distance                           189.0
carrier_delay                          0
weather_delay                          0
nas_delay                              0
security_delay                         0
late_aircraft_delay                    0

In [ ]:


# match varibles

import pandas as pd

raw_df = df1.copy()

raw_df["FL_DATE"] = pd.to_datetime(raw_df["FL_DATE"], errors="coerce")

raw_df["origin_city_name"] = raw_df["ORIGIN_CITY"]
raw_df["origin_state_nm"] = raw_df["ORIGIN_CITY"].astype(str).str.extract(r",\s*([^,]+)$")[0]

raw_df["dest_city_name"] = raw_df["DEST_CITY"]
raw_df["dest_state_nm"] = raw_df["DEST_CITY"].astype(str).str.extract(r",\s*([^,]+)$")[0]

state_map = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DC": "District of Columbia",
    "DE": "Delaware",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "IA": "Iowa",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "MA": "Massachusetts",
    "MD": "Maryland",
    "ME": "Maine",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MO": "Missouri",
    "MS": "Mississippi",
    "MT": "Montana",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "NE": "Nebraska",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NV": "Nevada",
    "NY": "New York",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "PR": "Puerto Rico",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VA": "Virginia",
    "VI": "U.S. Virgin Islands",
    "VT": "Vermont",
    "WA": "Washington",
    "WI": "Wisconsin",
    "WV": "West Virginia",
    "WY": "Wyoming",
    "TT": "TT"
}

raw_df["origin_state_nm"] = raw_df["origin_state_nm"].map(state_map).fillna(raw_df["origin_state_nm"])
raw_df["dest_state_nm"] = raw_df["dest_state_nm"].map(state_map).fillna(raw_df["dest_state_nm"])

table1_df = pd.DataFrame({
    "year": raw_df["FL_DATE"].dt.year,
    "month": raw_df["FL_DATE"].dt.month,
    "day_of_month": raw_df["FL_DATE"].dt.day,
    "day_of_week": raw_df["FL_DATE"].dt.dayofweek + 1,
    "fl_date": raw_df["FL_DATE"],
    "op_unique_carrier": raw_df["AIRLINE_CODE"],
    "op_carrier_fl_num": raw_df["FL_NUMBER"],
    "origin": raw_df["ORIGIN"],
    "origin_city_name": raw_df["origin_city_name"],
    "origin_state_nm": raw_df["origin_state_nm"],
    "dest": raw_df["DEST"],
    "dest_city_name": raw_df["dest_city_name"],
    "dest_state_nm": raw_df["dest_state_nm"],
    "crs_dep_time": raw_df["CRS_DEP_TIME"],
    "dep_time": raw_df["DEP_TIME"],
    "dep_delay": raw_df["DEP_DELAY"],
    "taxi_out": raw_df["TAXI_OUT"],
    "wheels_off": raw_df["WHEELS_OFF"],
    "wheels_on": raw_df["WHEELS_ON"],
    "taxi_in": raw_df["TAXI_IN"],
    "crs_arr_time": raw_df["CRS_ARR_TIME"],
    "arr_time": raw_df["ARR_TIME"],
    "arr_delay": raw_df["ARR_DELAY"],
    "cancelled": raw_df["CANCELLED"].fillna(0).astype("Int64"),
    "cancellation_code": raw_df["CANCELLATION_CODE"],
    "diverted": raw_df["DIVERTED"].fillna(0).astype("Int64"),
    "crs_elapsed_time": raw_df["CRS_ELAPSED_TIME"],
    "actual_elapsed_time": raw_df["ELAPSED_TIME"],
    "air_time": raw_df["AIR_TIME"],
    "distance": raw_df["DISTANCE"],
    "carrier_delay": raw_df["DELAY_DUE_CARRIER"].fillna(0),
    "weather_delay": raw_df["DELAY_DUE_WEATHER"].fillna(0),
    "nas_delay": raw_df["DELAY_DUE_NAS"].fillna(0),
    "security_delay": raw_df["DELAY_DUE_SECURITY"].fillna(0),
    "late_aircraft_delay": raw_df["DELAY_DUE_LATE_AIRCRAFT"].fillna(0),
})

      origin_city_name       origin_state_nm         dest_city_name  \
0  Fort Lauderdale, FL               Florida             Newark, NJ
1      Minneapolis, MN             Minnesota            Seattle, WA
2           Denver, CO              Colorado        Minneapolis, MN
3      Minneapolis, MN             Minnesota      San Francisco, CA
4          Orlando, FL               Florida  Dallas/Fort Worth, TX
5           Dallas, TX                 Texas      Oklahoma City, OK
6       Washington, DC  District of Columbia             Boston, MA
7       Huntsville, AL               Alabama         Washington, DC
8          Houston, TX                 Texas        Los Angeles, CA
9          Seattle, WA            Washington          Fairbanks, AK

          dest_state_nm
0            New Jersey
1            Washington
2             Minnesota
3            California
4                 Texas
5              Oklahoma
6         Massachusetts
7  District of Columbia
8            California
9                Alaska

In [ ]:
# complete merge two data sets.

df = pd.concat([table1_df, df2], ignore_index=True)
print(df.shape)
print(df.head())

(10079081, 35)
   year  month  day_of_month  day_of_week              fl_date  \
0  2019      1             9            3  2019-01-09 00:00:00
1  2022     11            19            6  2022-11-19 00:00:00
2  2022      7            22            5  2022-07-22 00:00:00
3  2023      3             6            1  2023-03-06 00:00:00
4  2020      2            23            7  2020-02-23 00:00:00

  op_unique_carrier  op_carrier_fl_num origin     origin_city_name  \
0                UA             1562.0    FLL  Fort Lauderdale, FL
1                DL             1149.0    MSP      Minneapolis, MN
2                UA              459.0    DEN           Denver, CO
3                DL             2295.0    MSP      Minneapolis, MN
4                NK              407.0    MCO          Orlando, FL

  origin_state_nm dest         dest_city_name dest_state_nm  crs_dep_time  \
0         Florida  EWR             Newark, NJ    New Jersey          1155
1       Minnesota  SEA            Seattle, WA    Washington          2120
2        Colorado  MSP        Minneapolis, MN     Minnesota           954
3       Minnesota  SFO      San Francisco, CA    California          1609
4         Florida  DFW  Dallas/Fort Worth, TX         Texas          1840

   dep_time  dep_delay  taxi_out  wheels_off  wheels_on  taxi_in  \
0    1151.0       -4.0      19.0      1210.0     1443.0      4.0
1    2114.0       -6.0       9.0      2123.0     2232.0     38.0
2    1000.0        6.0      20.0      1020.0     1247.0      5.0
3    1608.0       -1.0      27.0      1635.0     1844.0      9.0
4    1838.0       -2.0      15.0      1853.0     2026.0     14.0

   crs_arr_time  arr_time  arr_delay  cancelled cancellation_code  diverted  \
0          1501    1447.0      -14.0          0               NaN         0
1          2315    2310.0       -5.0          0               NaN         0
2          1252    1252.0        0.0          0               NaN         0
3          1829    1853.0       24.0          0               NaN         0
4          2041    2040.0       -1.0          0               NaN         0

   crs_elapsed_time  actual_elapsed_time  air_time  distance  carrier_delay  \
0             186.0                176.0     153.0    1065.0            0.0
1             235.0                236.0     189.0    1399.0            0.0
2             118.0                112.0      87.0     680.0            0.0
3             260.0                285.0     249.0    1589.0            0.0
4             181.0                182.0     153.0     985.0            0.0

   weather_delay  nas_delay  security_delay  late_aircraft_delay
0            0.0        0.0             0.0                  0.0
1            0.0        0.0             0.0                  0.0
2            0.0        0.0             0.0                  0.0
3            0.0       24.0             0.0                  0.0
4            0.0        0.0             0.0                  0.0

In [26]:
# check missing values for each column
print("Missing values per column:")
print(df.isna().sum())

print("\nNumber of duplicated rows:")
print(df.duplicated().sum())

Missing values per column:
year                         0
month                        0
day_of_month                 0
day_of_week                  0
fl_date                      0
op_unique_carrier            0
op_carrier_fl_num            1
origin                       0
origin_city_name             0
origin_state_nm              0
dest                         0
dest_city_name               0
dest_state_nm                0
crs_dep_time                 0
dep_time                170274
dep_delay               170614
taxi_out                174540
wheels_off              174540
wheels_on               177800
taxi_in                 177800
crs_arr_time                 0
arr_time                177796
arr_delay               200012
cancelled                    0
cancellation_code      9903626
diverted                     0
crs_elapsed_time            15
actual_elapsed_time     200012
air_time                200012
distance                     0
carrier_delay                0
weather_delay                0
nas_delay                    0
security_delay               0
late_aircraft_delay          0
dtype: int64

Number of duplicated rows:
0

In [29]:
cols1 = ["year", "month", "day_of_month", "day_of_week", "fl_date"]
print("Missing values:")
print(df[cols1].isna().sum())

Missing values:
year            0
month           0
day_of_month    0
day_of_week     0
fl_date         0
dtype: int64

In [30]:
abnormal_month = df[(df["month"] < 1) | (df["month"] > 12)]
abnormal_day = df[(df["day_of_month"] < 1) | (df["day_of_month"] > 31)]
abnormal_week = df[(df["day_of_week"] < 1) | (df["day_of_week"] > 7)]

print("\nAbnormal month:", len(abnormal_month))
print("Abnormal day_of_month:", len(abnormal_day))
print("Abnormal day_of_week:", len(abnormal_week))

Abnormal month: 0
Abnormal day_of_month: 0
Abnormal day_of_week: 0

In [31]:
df["fl_date"] = pd.to_datetime(df["fl_date"], errors="coerce")

print("\nfl_date parse failed:")
print(df["fl_date"].isna().sum())

fl_date parse failed:
0

In [32]:
rebuild = pd.to_datetime(
    {
        "year": df["year"],
        "month": df["month"],
        "day": df["day_of_month"]
    },
    errors="coerce"
)

mask = df["fl_date"].notna() & rebuild.notna()

mismatch = df.loc[mask & (df["fl_date"] != rebuild)]

print("Date mismatch rows:", len(mismatch))

Date mismatch rows: 0

Part 2
op_unique_carrier

op_carrier_fl_num

origin

origin_city_name

origin_state_nm

dest

dest_city_name

dest_state_nm

In [34]:
# varible: op_unique_carrier

s = df["op_unique_carrier"].astype("string").str.strip()
mask_bad = s.isna() | (s.str.len() != 2)
# every data point is good under the rule: no missing value no values are more than two characters
n_bad = int(mask_bad.sum())

In [35]:
# varible: op_carrier_fl_num    

s_raw_op = df["op_carrier_fl_num"].astype("string").str.strip()
s = s_raw_op.mask(s_raw_op.eq(""), pd.NA)

# numeric for validation
num = pd.to_numeric(s, errors="coerce")


mask_missing = s.isna()
mask_not_int = (~mask_missing) & (num.isna() | (num % 1 != 0))
int_val = num.round(0).astype("Int64")

# no more than 4 digits
mask_gt_4_digits = (~mask_missing) & (~mask_not_int) & ((int_val < 0) | (int_val > 9999))

mask_bad = mask_missing | mask_not_int | mask_gt_4_digits

# summary counts

summary = pd.DataFrame(
    {
        "total_rows": [len(df)],
        "missing": [int(mask_missing.sum())],
        "not_int": [int(mask_not_int.sum())],
        "gt_4_digits": [int(mask_gt_4_digits.sum())],
        "bad_total": [int(mask_bad.sum())],
    }
)
summary
# find one missing value

   total_rows  missing  not_int  gt_4_digits  bad_total
0    10079081        1        0            0          1

In [36]:
# identify the missing value loction
missing_obs = df.loc[mask_missing].copy()
missing_obs["_op_carrier_fl_num_clean"] = s[mask_missing].to_numpy()

missing_obs

,year,month,day_of_month,day_of_week,fl_date,op_unique_carrier,op_carrier_fl_num,origin,origin_city_name,origin_state_nm,dest,dest_city_name,dest_state_nm,crs_dep_time,dep_time,dep_delay,taxi_out,wheels_off,wheels_on,taxi_in,crs_arr_time,arr_time,arr_delay,cancelled,cancellation_code,diverted,crs_elapsed_time,actual_elapsed_time,air_time,distance,carrier_delay,weather_delay,nas_delay,security_delay,late_aircraft_delay,_op_carrier_fl_num_clean
7587670,2024,8,25,7,2024-08-25,F9,NaN,MIA,"Miami, FL",Florida,ATL,"Atlanta, GA",Georgia,600,554.0,-6.0,28.0,622.0,751.0,11.0,807,802.0,-5.0,0,NaN,0,127.0,128.0,89.0,594.0,0.0,0.0,0.0,0.0,0.0,<NA>

In [37]:
# input value 7587670 in dataset
fill_value = 7587670


op = int_val.reindex(df.index)
op.loc[mask_bad.reindex(df.index, fill_value=False)] = fill_value

df["op_carrier_fl_num"] = op.astype("int64")

In [38]:
# varible: origin  


# non-missing and exactly 3 characters 
s_raw_or = df["origin"].astype("string").str.strip()
s = s_raw_or.mask(s_raw_or.eq(""), pd.NA)

mask_missing = s.isna()
mask_not_3 = (~mask_missing) & (s.str.len() != 3)
mask_bad = mask_missing | mask_not_3

# summary

pd.DataFrame(
    {
        "total_rows": [len(df)],
        "missing": [int(mask_missing.sum())],
        "not_3_chars": [int(mask_not_3.sum())],
        "bad_total": [int(mask_bad.sum())],
    }
)

# all good

   total_rows  missing  not_3_chars  bad_total
0    10079081        0            0          0

In [39]:
# origin_city_name: "New York, NY" "Minneapolis, MN"
# to "New York", "Minneapolis"
# origin_state: "NY", "MN"

# check missing value: no missing

s_raw = df["origin_city_name"].astype("string").str.strip()
s = s_raw.mask(s_raw.eq(""), pd.NA)

mask_missing = s.isna()


pd.DataFrame(
    {
        "total_rows": [len(df)],
        "missing": [int(mask_missing.sum())],
    }
)

   total_rows  missing
0    10079081        0

In [40]:
# split stste name to a new varible: origin_state_abbr


# origin_city_name: "New York, NY" "Minneapolis, MN"
# to "New York", "Minneapolis"
# origin_state: "NY", "MN"


s_raw1 = df["origin_city_name"].astype("string").str.strip()

origin_state_abbr = (
    s_raw1
    .str.extract(r",\s*([A-Za-z]{2})\s*$", expand=False)
    .str.upper()
)

origin_city_name = (
    s_raw1
    .str.replace(r",\s*[A-Za-z]{2}\s*$", "", regex=True)
    .str.strip()
)

df["origin_state_abbr"] = origin_state_abbr
df["origin_city_name"] = origin_city_name

# check
df[["origin_city_name", "origin_state_abbr"]].head()

  origin_city_name origin_state_abbr
0  Fort Lauderdale                FL
1      Minneapolis                MN
2           Denver                CO
3      Minneapolis                MN
4          Orlando                FL

In [41]:
#check state name correction

us_state_abbr = [
    "AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA",
    "HI","ID","IL","IN","IA","KS","KY","LA","ME","MD",
    "MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ",
    "NM","NY","NC","ND","OH","OK","OR","PA","RI","SC",
    "SD","TN","TX","UT","VT","VA","WA","WV","WI","WY",
    "DC","PR", "VI", "TT"
]

abbr = df["origin_state_abbr"].astype("string").str.strip().str.upper()

mask_bad = abbr.isna() | (~abbr.isin(us_state_abbr))

pd.DataFrame(
    {
        "total_rows": [len(df)],
        "missing": [int(abbr.isna().sum())],
        "not_in_us_state_list": [int((~abbr.isna() & ~abbr.isin(us_state_abbr)).sum())],
        "bad_total": [int(mask_bad.sum())],
    }
)

# all good

   total_rows  missing  not_in_us_state_list  bad_total
0    10079081        0                     0          0

In [42]:
# origin_state_nm


s_raw_sta = df["origin_state_nm"].astype("string").str.strip()
s = s_raw_sta.mask(s_raw_sta.eq(""), pd.NA)

mask_missing = s.isna()


pd.DataFrame(
    {
        "total_rows": [len(df)],
        "missing": [int(mask_missing.sum())],
    }
)

# no missig value

   total_rows  missing
0    10079081        0

In [55]:
full_names = [
    "Texas","California","Florida","Illinois","Georgia","New York","Colorado","North Carolina","Virginia",
    "Arizona","Nevada","Washington","Michigan","Pennsylvania","Tennessee","Massachusetts","New Jersey",
    "Minnesota","Missouri","Hawaii","Utah","Maryland","Ohio","Oregon","Kentucky","Louisiana","South Carolina",
    "Indiana","Wisconsin","Oklahoma","Puerto Rico","Alaska","Alabama","Idaho","Arkansas","New Mexico",
    "Nebraska","Montana","Iowa","Connecticut","North Dakota","Maine","Rhode Island","Kansas","South Dakota",
    "Mississippi","Wyoming","Vermont","U.S. Virgin Islands","New Hampshire","West Virginia",
    "U.S. Pacific Trust Territories and Possessions", "Delaware"
]



mask_bad = s_raw_sta.isna() | (~s_raw_sta.isin(full_names))

pd.DataFrame(
    {
        "total_rows": [len(df)],
        "missing": [int(s_raw_sta.isna().sum())],
        "not_in_us_state_list": [int((~s_raw_sta.isna() & ~s_raw_sta.isin(full_names)).sum())],
        "bad_total": [int(mask_bad.sum())],
    }
)

   total_rows  missing  not_in_us_state_list  bad_total
0    10079081        0                     0          0

In [56]:
mask_washington_va = (
    df["origin_city_name"].astype("string").str.strip().eq("Washington")
    & df["origin"].isin(["DCA", "IAD"])
)

df.loc[mask_washington_va, "origin_state_nm"] = "Virginia"

df["origin_state_nm"] = (
    df["origin_state_nm"]
    .astype("string")
    .str.strip()
    .replace({
        "TT": "U.S. Pacific Trust Territories and Possessions"
    })
)

In [57]:
s_raw_sta = df["origin_state_nm"].astype("string").str.strip()

mask_bad = s_raw_sta.isna() | (~s_raw_sta.isin(full_names))

pd.DataFrame(
    {
        "total_rows": [len(df)],
        "missing": [int(s_raw_sta.isna().sum())],
        "not_in_us_state_list": [int((~s_raw_sta.isna() & ~s_raw_sta.isin(full_names)).sum())],
        "bad_total": [int(mask_bad.sum())],
    }
)

bad_rows = df.loc[mask_bad, [
    "origin_city_name",
    "origin_state_nm",
    "origin",
    "dest",
    "fl_date"
]].copy()

print(bad_rows.head(50))

Empty DataFrame
Columns: [origin_city_name, origin_state_nm, origin, dest, fl_date]
Index: []

In [58]:
# varible: dest  


# non-missing and exactly 3 characters 
s_raw_d = df["dest"].astype("string").str.strip()
s = s_raw_d.mask(s_raw_d.eq(""), pd.NA)

mask_missing = s.isna()
mask_not_3 = (~mask_missing) & (s.str.len() != 3)
mask_bad = mask_missing | mask_not_3

# summary

pd.DataFrame(
    {
        "total_rows": [len(df)],
        "missing": [int(mask_missing.sum())],
        "not_3_chars": [int(mask_not_3.sum())],
        "bad_total": [int(mask_bad.sum())],
    }
)

# all good

   total_rows  missing  not_3_chars  bad_total
0    10079081        0            0          0

In [59]:
# dest_city_name: "Detroit, MI"
# to "Detroit"
# dest_state: "MI"


s_raw1 = df["dest_city_name"].astype("string").str.strip()

dest_state_abbr = (
    s_raw1
    .str.extract(r",\s*([A-Za-z]{2})\s*$", expand=False)
    .str.upper()
)

dest_city_name = (
    s_raw1
    .str.replace(r",\s*[A-Za-z]{2}\s*$", "", regex=True)
    .str.strip()
)

df["dest_state_abbr"] = dest_state_abbr
df["dest_city_name"] = dest_city_name

# check
df[["dest_city_name", "dest_state_abbr"]].head()

      dest_city_name dest_state_abbr
0             Newark              NJ
1            Seattle              WA
2        Minneapolis              MN
3      San Francisco              CA
4  Dallas/Fort Worth              TX

In [ ]:
#check state name

us_state_abbr = [
    "AL","AK","AZ","AR","CA","CO","CT","DE","FL","GA",
    "HI","ID","IL","IN","IA","KS","KY","LA","ME","MD",
    "MA","MI","MN","MS","MO","MT","NE","NV","NH","NJ",
    "NM","NY","NC","ND","OH","OK","OR","PA","RI","SC",
    "SD","TN","TX","UT","VT","VA","WA","WV","WI","WY",
    "DC","PR", "VI", "TT"
]

abbr = df["dest_state_abbr"].astype("string").str.strip().str.upper()

mask_bad = abbr.isna() | (~abbr.isin(us_state_abbr))

pd.DataFrame(
    {
        "total_rows": [len(df)],
        "missing": [int(abbr.isna().sum())],
        "not_in_us_state_list": [int((~abbr.isna() & ~abbr.isin(us_state_abbr)).sum())],
        "bad_total": [int(mask_bad.sum())],
    }
)

#all good

   total_rows  missing  not_in_us_state_list  bad_total
0    10079081        0                     0          0

In [62]:
# dest_state_nm


s_raw = df["dest_state_nm"].astype("string").str.strip()
s = s_raw.mask(s_raw.eq(""), pd.NA)

mask_missing = s.isna()


pd.DataFrame(
    {
        "total_rows": [len(df)],
        "missing": [int(mask_missing.sum())],
    }
)


full_names = [
    "Texas","California","Florida","Illinois","Georgia","New York","Colorado","North Carolina","Virginia",
    "Arizona","Nevada","Washington","Michigan","Pennsylvania","Tennessee","Massachusetts","New Jersey",
    "Minnesota","Missouri","Hawaii","Utah","Maryland","Ohio","Oregon","Kentucky","Louisiana","South Carolina",
    "Indiana","Wisconsin","Oklahoma","Puerto Rico","Alaska","Alabama","Idaho","Arkansas","New Mexico",
    "Nebraska","Montana","Iowa","Connecticut","North Dakota","Maine","Rhode Island","Kansas","South Dakota",
    "Mississippi","Wyoming","Vermont","U.S. Virgin Islands","New Hampshire","West Virginia",
    "U.S. Pacific Trust Territories and Possessions","Delaware"
]



mask_bad = s_raw.isna() | (~s_raw.isin(full_names))

pd.DataFrame(
    {
        "total_rows": [len(df)],
        "missing": [int(s_raw.isna().sum())],
        "not_in_us_state_list": [int((~s_raw.isna() & ~s_raw.isin(full_names)).sum())],
        "bad_total": [int(mask_bad.sum())],
    }
)

# all good

   total_rows  missing  not_in_us_state_list  bad_total
0    10079081        0                 79680      79680

In [63]:
mask_washington_va_dest = (
    df["dest_city_name"].astype("string").str.strip().eq("Washington")
    & df["dest"].isin(["DCA", "IAD"])
)

df.loc[mask_washington_va_dest, "dest_state_nm"] = "Virginia"

df["dest_state_nm"] = (
    df["dest_state_nm"]
    .astype("string")
    .str.strip()
    .replace({
        "TT": "U.S. Pacific Trust Territories and Possessions"
    })
)

# part 3

In [65]:

cols3_1 = ["crs_dep_time","dep_time","dep_delay","taxi_out","taxi_in","cancelled"]

In [66]:
print("Missing crs_dep_time:")
print(df["crs_dep_time"].isna().sum())

Missing crs_dep_time:
0

In [68]:
import numpy as np
mask_cancel = df["cancelled"] == 1

df.loc[mask_cancel, ["dep_delay","taxi_out","taxi_in"]] = np.nan

In [69]:
s = pd.to_numeric(df["crs_dep_time"], errors="coerce")
s_str = s.dropna().astype(int).astype(str).str.zfill(4)

df["crs_dep_time_tmp"] = pd.NA

df.loc[s_str.index, "crs_dep_time_tmp"] = (
    pd.to_datetime(s_str, format="%H%M", errors="coerce")
      .dt.strftime("%H:%M")
)
s = pd.to_numeric(df["dep_time"], errors="coerce")
s_str = s.dropna().astype(int).astype(str).str.zfill(4)

df["dep_time_tmp"] = pd.NA

df.loc[s_str.index, "dep_time_tmp"] = (
    pd.to_datetime(s_str, format="%H%M", errors="coerce")
      .dt.strftime("%H:%M")
)
df["crs_dep_time"] = df["crs_dep_time_tmp"]
df.drop(columns=["crs_dep_time_tmp"], inplace=True)

df["dep_time"] = df["dep_time_tmp"]
df.drop(columns=["dep_time_tmp"], inplace=True)

In [70]:
df["dep_time"] = pd.to_datetime(
    df["dep_time"],
    format="%H:%M",
    errors="coerce"
).dt.time
df["crs_dep_time"] = pd.to_datetime(
    df["crs_dep_time"],
    format="%H:%M",
    errors="coerce"
).dt.time

In [71]:
crs = pd.to_numeric(df["crs_dep_time"], errors="coerce")
dep = pd.to_numeric(df["dep_time"], errors="coerce")

crs_h = crs // 100
crs_m = crs % 100
dep_h = dep // 100
dep_m = dep % 100

valid = (
    crs_h.between(0, 23) & crs_m.between(0, 59) &
    dep_h.between(0, 23) & dep_m.between(0, 59)
)

crs_min = crs_h * 60 + crs_m
dep_min = dep_h * 60 + dep_m

raw = dep_min - crs_min

mask = df["dep_delay"].notna() & valid

delta = df["dep_delay"] - raw

ok = (delta % 1440 == 0)

delay_mismatch = df.loc[mask & (~ok)]

print("dep_delay mismatch:", len(delay_mismatch))

dep_delay mismatch: 0

In [72]:
neg_taxi_out = df[df["taxi_out"] < 0]
neg_taxi_in  = df[df["taxi_in"] < 0]

print("\nNegative taxi_out:", len(neg_taxi_out))
print("Negative taxi_in:", len(neg_taxi_in))

Negative taxi_out: 0
Negative taxi_in: 0

In [73]:
s = pd.to_numeric(df["wheels_off"], errors="coerce")
s_str = s.dropna().astype(int).astype(str).str.zfill(4)

df["wheels_off_tmp"] = pd.NA

df.loc[s_str.index, "wheels_off_tmp"] = (
    pd.to_datetime(s_str, format="%H%M", errors="coerce")
      .dt.strftime("%H:%M")
)
s = pd.to_numeric(df["wheels_on"], errors="coerce")
s_str = s.dropna().astype(int).astype(str).str.zfill(4)

df["wheels_on_tmp"] = pd.NA

df.loc[s_str.index, "wheels_on_tmp"] = (
    pd.to_datetime(s_str, format="%H%M", errors="coerce")
      .dt.strftime("%H:%M")
)
s = pd.to_numeric(df["crs_arr_time"], errors="coerce")
s_str = s.dropna().astype(int).astype(str).str.zfill(4)

df["crs_arr_time_tmp"] = pd.NA

df.loc[s_str.index, "crs_arr_time_tmp"] = (
    pd.to_datetime(s_str, format="%H%M", errors="coerce")
      .dt.strftime("%H:%M")
)
     
s = pd.to_numeric(df["arr_time"], errors="coerce")
s_str = s.dropna().astype(int).astype(str).str.zfill(4)

df["arr_time_tmp"] = pd.NA

df.loc[s_str.index, "arr_time_tmp"] = (
    pd.to_datetime(s_str, format="%H%M", errors="coerce")
      .dt.strftime("%H:%M")
)

In [74]:
df["wheels_off"] = df["wheels_off_tmp"]
df.drop(columns=["wheels_off_tmp"], inplace=True)

df["wheels_on"] = df["wheels_on_tmp"]
df.drop(columns=["wheels_on_tmp"], inplace=True)

df["crs_arr_time"] = df["crs_arr_time_tmp"]
df.drop(columns=["crs_arr_time_tmp"], inplace=True)

df["arr_time"] = df["arr_time_tmp"]
df.drop(columns=["arr_time_tmp"], inplace=True)
df["wheels_off"] = pd.to_datetime(
    df["wheels_off"],
    format="%H:%M",
    errors="coerce"
).dt.time
df["wheels_on"] = pd.to_datetime(
    df["wheels_on"],
    format="%H:%M",
    errors="coerce"
).dt.time

df["arr_time"] = pd.to_datetime(
    df["arr_time"],
    format="%H:%M",
    errors="coerce"
).dt.time
df["crs_arr_time"] = pd.to_datetime(
    df["crs_arr_time"],
    format="%H:%M",
    errors="coerce"
).dt.time

In [75]:
crs = pd.to_numeric(df["crs_arr_time"], errors="coerce")
arr = pd.to_numeric(df["arr_time"], errors="coerce")

crs_h = crs // 100
crs_m = crs % 100
arr_h = arr // 100
arr_m = arr % 100

valid = (
    crs_h.between(0, 23) & crs_m.between(0, 59) &
    arr_h.between(0, 23) & arr_m.between(0, 59)
)

crs_min = crs_h * 60 + crs_m
arr_min = arr_h * 60 + arr_m

raw = arr_min - crs_min

mask = df["arr_delay"].notna() & valid

delta = df["arr_delay"] - raw

ok = (delta % 1440 == 0)

delay_mismatch = df.loc[mask & (~ok)]

print("arr_delay mismatch:", len(delay_mismatch))

arr_delay mismatch: 0

# part 4

In [76]:
# varible: cancelled

c_raw = df["cancelled"].astype("string").str.strip()
c = c_raw.mask(c_raw.eq(""), pd.NA)

c_num = pd.to_numeric(c, errors="coerce")

mask_c_missing = c.isna()
mask_c_not_int = (~mask_c_missing) & (c_num.isna() | (c_num % 1 != 0))
c_int = c_num.round(0).astype("Int64")
mask_c_not_01 = (~mask_c_missing) & (~mask_c_not_int) & (~c_int.isin([0, 1]))

mask_c_bad = mask_c_missing | mask_c_not_int | mask_c_not_01

cancelled_summary = pd.DataFrame(
    {
        "total_rows": [len(df)],
        "missing": [int(mask_c_missing.sum())],
        "not_int": [int(mask_c_not_int.sum())],
        "not_0_or_1": [int(mask_c_not_01.sum())],
        "bad_total": [int(mask_c_bad.sum())],
    }
)
cancelled_summary


# all good

   total_rows  missing  not_int  not_0_or_1  bad_total
0    10079081        0        0           0          0

In [77]:
mask_cancelled_1 = c_int.eq(1)

# related variables: set to NaN when cancelled == 1
rel_cols = [
    "dep_time", "dep_delay", "taxi_out", "wheels_off",
    "wheels_on", "taxi_in", "arr_time", "arr_delay","actual_elapsed_time", "air_time"
]

df.loc[mask_cancelled_1, rel_cols] = np.nan

In [78]:
# cancelled code


allowed = ["A", "B", "C", "D"]

# cancelled
c_raw = df["cancelled"].astype("string").str.strip()
c = c_raw.mask(c_raw.eq(""), pd.NA)
c_int = pd.to_numeric(c, errors="coerce").round(0).astype("Int64")


cc_raw = df["cancellation_code"].astype("string").str.strip()
cc = cc_raw.mask(cc_raw.eq(""), pd.NA).str.upper()

mask_cc_invalid_value = cc.notna() & (~cc.isin(allowed))

mask_cancelled0_code_present = c_int.eq(0) & cc.notna()
mask_cancelled1_code_missing = c_int.eq(1) & cc.isna()
mask_cancelled1_code_invalid = c_int.eq(1) & mask_cc_invalid_value

mask_bad = mask_cc_invalid_value | mask_cancelled0_code_present | mask_cancelled1_code_missing | mask_cancelled1_code_invalid

pd.DataFrame(
    {
        "total_rows": [len(df)],
        "invalid_code_value": [int(mask_cc_invalid_value.sum())],
        "cancelled_0_but_code_present": [int(mask_cancelled0_code_present.sum())],
        "cancelled_1_but_code_missing": [int(mask_cancelled1_code_missing.sum())],
        "cancelled_1_but_code_invalid": [int(mask_cancelled1_code_invalid.sum())],
        "bad_total": [int(mask_bad.sum())],
    }
)


# all good

,total_rows,invalid_code_value,cancelled_0_but_code_present,cancelled_1_but_code_missing,cancelled_1_but_code_invalid,bad_total
0,10079081,0,0,0,0,0

In [88]:
# crs_elapsed_time non-missing and >= 0

s_rawcrs = df["crs_elapsed_time"].astype("string").str.strip()
s = s_rawcrs.mask(s_rawcrs.eq(""), pd.NA)

num = pd.to_numeric(s, errors="coerce")

mask_missing = num.isna()
mask_negative = num.notna() & (num < 0)
mask_bad = mask_missing | mask_negative

pd.DataFrame(
    {
        "total_rows": [len(df)],
        "missing": [int(mask_missing.sum())],
        "negative": [int(mask_negative.sum())],
        "bad_total": [int(mask_bad.sum())],
    }
)

   total_rows  missing  negative  bad_total
0    10054524       15         1         16

In [89]:
bad_rows = df.loc[mask_bad].copy()


df = df.loc[~mask_bad].copy().reset_index(drop=True)

In [90]:
s_rawcrs = df["crs_elapsed_time"].astype("string").str.strip()
s = s_rawcrs.mask(s_rawcrs.eq(""), pd.NA)

num = pd.to_numeric(s, errors="coerce")

mask_missing = num.isna()
mask_negative = num.notna() & (num < 0)
mask_bad = mask_missing | mask_negative

pd.DataFrame(
    {
        "total_rows": [len(df)],
        "missing": [int(mask_missing.sum())],
        "negative": [int(mask_negative.sum())],
        "bad_total": [int(mask_bad.sum())],
    }
)

   total_rows  missing  negative  bad_total
0    10054508        0         0          0

In [80]:
# actual_elapsed_time

# >= 0
# if flight cancelled then = NaN already check above

s_rawcrs = df["actual_elapsed_time"].astype("string").str.strip()
s = s_rawcrs.mask(s_rawcrs.eq(""), pd.NA)

num = pd.to_numeric(s, errors="coerce")

mask_missing = num.isna()
mask_negative = num.notna() & (num < 0)

pd.DataFrame(
    {
        "total_rows": [len(df)],
        "missing": [int(mask_missing.sum())],
        "negative": [int(mask_negative.sum())]
    }
)

   total_rows  missing  negative
0    10079081   200012         0

In [81]:
c_raw = df["cancelled"].astype("string").str.strip()
c = c_raw.mask(c_raw.eq(""), pd.NA)
c_int = pd.to_numeric(c, errors="coerce").round(0).astype("Int64")

# cancelled = 0 but 'actual_elapsed_time' is missing
mask_bad = c_int.eq(0) & mask_missing


pd.DataFrame(
    {
        "total_rows": [len(df)],
        "cancelled_0_but_missing_actual_elapsed_time": [int(mask_bad.sum())],
    }
)

# remove where cancelled = 0 but 'actual_elapsed_time' is missing
df = df.drop(index=df.index[mask_bad])

In [82]:
#air_time

s_rawcrs = df["air_time"].astype("string").str.strip()
s = s_rawcrs.mask(s_rawcrs.eq(""), pd.NA)

num = pd.to_numeric(s, errors="coerce")

mask_missing = num.isna()
mask_negative = num.notna() & (num < 0)

pd.DataFrame(
    {
        "total_rows": [len(df)],
        "missing": [int(mask_missing.sum())],
        "negative": [int(mask_negative.sum())]
    }
)

   total_rows  missing  negative
0    10054524   175455         0

In [83]:
c_raw = df["cancelled"].astype("string").str.strip()
c = c_raw.mask(c_raw.eq(""), pd.NA)
c_int = pd.to_numeric(c, errors="coerce").round(0).astype("Int64")

# cancelled = 0 but 'actual_elapsed_time' is missing
mask_bad = c_int.eq(0) & mask_missing



pd.DataFrame(
    {
        "total_rows": [len(df)],
        "cancelled_0_but_missing_actual_elapsed_time": [int(mask_bad.sum())],
    }
)

# all good

   total_rows  cancelled_0_but_missing_actual_elapsed_time
0    10054524                                            0

In [84]:
# distance

s_rawdi = df["distance"].astype("string").str.strip()
s = s_rawdi.mask(s_rawdi.eq(""), pd.NA)

num = pd.to_numeric(s, errors="coerce")

mask_missing = num.isna()
mask_negative = num.notna() & (num < 0)

pd.DataFrame(
    {
        "total_rows": [len(df)],
        "missing": [int(mask_missing.sum())],
        "negative": [int(mask_negative.sum())]
    }
)

# all good

   total_rows  missing  negative
0    10054524        0         0

In [85]:
cols6 = ["carrier_delay", "weather_delay", "nas_delay", "security_delay", "late_aircraft_delay"]
neg_mask = (df[cols6] < 0).any(axis=1)

neg_rows = df.loc[neg_mask, cols6]

print("Rows with negative delay components:", len(neg_rows))

Rows with negative delay components: 0

In [ ]:
mask_arr = df["arr_delay"] > 0

sum_comp = df[cols6].sum(axis=1)

arr_delay_mismatch = mask_arr & (sum_comp != df["arr_delay"])

print("arr_delay sum mismatch rows:", arr_delay_mismatch.sum())

In [ ]:
df["arr_delay_consistent"] = True
df.loc[mask_arr, "arr_delay_consistent"] = (
    sum_comp[mask_arr] == df.loc[mask_arr, "arr_delay"]
)

In [ ]:
print("arr_delay > 0 rows:", mask_arr.sum())
print("consistent rows:",
      (mask_arr & (sum_comp == df["arr_delay"])).sum())
print("inconsistent rows:",
      (mask_arr & (sum_comp != df["arr_delay"])).sum())

In [ ]:
has_na_component = df[cols6].isna().any(axis=1)

(mask_arr & (sum_comp != df["arr_delay"]) & has_na_component).sum()

In [ ]:
less = mask_arr & (sum_comp < df["arr_delay"])
greater = mask_arr & (sum_comp > df["arr_delay"])

print("sum < arr_delay:", less.sum())
print("sum > arr_delay:", greater.sum())

In [ ]:
df.info()